/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teamproject;

/**
 *
 * @author ahmetsesli
 */
public class UpdateCustomer extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public UpdateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        buttonDone = new javax.swing.JButton();
        textFieldPostCode = new javax.swing.JTextField();
        labelColour = new javax.swing.JLabel();
        labelPostCode = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelFullName = new javax.swing.JLabel();
        labelLoggedIn = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        textFieldUsername = new javax.swing.JTextField();
        labelTelephone = new javax.swing.JLabel();
        textFieldFax = new javax.swing.JTextField();
        textFieldFullName = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldTelephone = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaAddress = new javax.swing.JTextArea();
        labelVehicles = new javax.swing.JLabel();
        labelRegistrationNo = new javax.swing.JLabel();
        labelMake = new javax.swing.JLabel();
        labelModel = new javax.swing.JLabel();
        labelChassisNo = new javax.swing.JLabel();
        labelLastMoTDate = new javax.swing.JLabel();
        labelEngineSerialNo = new javax.swing.JLabel();
        labelMoTDateFormat = new javax.swing.JLabel();
        textFieldEnginSerialNo = new javax.swing.JTextField();
        textFieldModel = new javax.swing.JTextField();
        textFieldMake = new javax.swing.JTextField();
        textFieldRegistrationNo = new javax.swing.JTextField();
        textFieldChassisNo = new javax.swing.JTextField();
        textFieldColour = new javax.swing.JTextField();
        buttonConfirmDiscount = new javax.swing.JButton();
        buttonSaveVehicleChanges = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        labelCustomerDetails = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listVehicles = new javax.swing.JList<>();
        buttonNewVehicle = new javax.swing.JButton();
        textFieldPercentage = new javax.swing.JTextField();
        checkBoxAccountHolder = new javax.swing.JCheckBox();
        labelCustomerInformation = new javax.swing.JLabel();
        labelVariableDiscount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPercentage = new javax.swing.JLabel();
        labelDiscountDetail = new javax.swing.JLabel();
        checkBoxDiscountPlan = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        textFieldSearchDiscountDetails = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        listBusinessType = new javax.swing.JList<>();
        textFieldLastServiceDay = new javax.swing.JTextField();
        textFieldLastServiceMonth = new javax.swing.JTextField();
        textFieldLastServiceYear = new javax.swing.JTextField();
        textFieldLastMoTYear = new javax.swing.JTextField();
        textFieldLastMoTDay = new javax.swing.JTextField();
        textFieldLastMoTMonth = new javax.swing.JTextField();
        checkBoxConfigurePayLater = new javax.swing.JCheckBox();
        labelLastServiceDate = new javax.swing.JLabel();
        labelServiceDateFormat = new javax.swing.JLabel();
        buttonSearchDiscountDetails = new javax.swing.JButton();
        buttonEditVehicle1 = new javax.swing.JButton();
        comboBoxDiscountPlan = new javax.swing.JComboBox<>();
        labelFax1 = new javax.swing.JLabel();
        buttonSetDiscountPlan1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        buttonDone.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonDone.setText("Done");
        jPanel1.add(buttonDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 660, -1, -1));
        jPanel1.add(textFieldPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 260, -1));

        labelColour.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelColour.setText("Colour:");
        jPanel1.add(labelColour, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        labelPostCode.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelPostCode.setText("Post Code:");
        jPanel1.add(labelPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        labelAddress.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelAddress.setText("Address:");
        jPanel1.add(labelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        labelEmail.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelEmail.setText("Email:");
        jPanel1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        labelFullName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFullName.setText("Full Name:");
        jPanel1.add(labelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        labelLoggedIn.setText("Logged In as:");
        jPanel1.add(labelLoggedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        buttonExit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonExit.setText("Exit");
        jPanel1.add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));
        jPanel1.add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 220, 30));

        labelTelephone.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelTelephone.setText("Telephone:");
        jPanel1.add(labelTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));
        jPanel1.add(textFieldFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 260, -1));
        jPanel1.add(textFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, -1));
        jPanel1.add(textFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 260, -1));
        jPanel1.add(textFieldTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 260, -1));

        textAreaAddress.setColumns(20);
        textAreaAddress.setRows(5);
        jScrollPane4.setViewportView(textAreaAddress);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 260, -1));

        labelVehicles.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelVehicles.setText("Vehicles:");
        jPanel1.add(labelVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        labelRegistrationNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelRegistrationNo.setText("Registration No:");
        jPanel1.add(labelRegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        labelMake.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelMake.setText("Make:");
        jPanel1.add(labelMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        labelModel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelModel.setText("Model:");
        jPanel1.add(labelModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        labelChassisNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelChassisNo.setText("Chassis No:");
        jPanel1.add(labelChassisNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        labelLastMoTDate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelLastMoTDate.setText("Last MoT Date: ");
        jPanel1.add(labelLastMoTDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 140, -1));

        labelEngineSerialNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelEngineSerialNo.setText("Engine Serial No:");
        jPanel1.add(labelEngineSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        labelMoTDateFormat.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelMoTDateFormat.setText("(dd/mm/yyyy)");
        jPanel1.add(labelMoTDateFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, -1, -1));
        jPanel1.add(textFieldEnginSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 250, -1));
        jPanel1.add(textFieldModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 250, -1));
        jPanel1.add(textFieldMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 250, -1));
        jPanel1.add(textFieldRegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 250, -1));
        jPanel1.add(textFieldChassisNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 250, -1));
        jPanel1.add(textFieldColour, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 250, -1));

        buttonConfirmDiscount.setText("Confirm");
        jPanel1.add(buttonConfirmDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 100, -1));

        buttonSaveVehicleChanges.setText("Save Changes");
        jPanel1.add(buttonSaveVehicleChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, 130, -1));

        jLabel59.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel59.setText("Full Name:");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        labelCustomerDetails.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        labelCustomerDetails.setText("Customer Details");
        jPanel1.add(labelCustomerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        buttonBack.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonBack.setText("Back");
        jPanel1.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        listVehicles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listVehicles);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 700, -1));

        buttonNewVehicle.setText("New Vehicle");
        jPanel1.add(buttonNewVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, -1, -1));
        jPanel1.add(textFieldPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 40, -1));

        checkBoxAccountHolder.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkBoxAccountHolder.setText("Account Holder");
        jPanel1.add(checkBoxAccountHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        labelCustomerInformation.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        labelCustomerInformation.setText("*Customer needs to be an Account");
        jPanel1.add(labelCustomerInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        labelVariableDiscount.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jPanel1.add(labelVariableDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel5.setText("holder to have a discount plan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        labelPercentage.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelPercentage.setText("%");
        jPanel1.add(labelPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, 20));

        labelDiscountDetail.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelDiscountDetail.setText("Details:");
        jPanel1.add(labelDiscountDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, 20));

        checkBoxDiscountPlan.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        checkBoxDiscountPlan.setText("Discount plan");
        jPanel1.add(checkBoxDiscountPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setText("or/and pay later");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        textFieldSearchDiscountDetails.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textFieldSearchDiscountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchDiscountDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldSearchDiscountDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 120, 20));

        listBusinessType.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listBusinessType);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 200, 120));

        textFieldLastServiceDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastServiceDayActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastServiceDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 30, 30));

        textFieldLastServiceMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastServiceMonthActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastServiceMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 30, 30));

        textFieldLastServiceYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastServiceYearActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastServiceYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 50, 30));

        textFieldLastMoTYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastMoTYearActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastMoTYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, 50, 30));

        textFieldLastMoTDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastMoTDayActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastMoTDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 30, 30));

        textFieldLastMoTMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastMoTMonthActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastMoTMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 30, 30));

        checkBoxConfigurePayLater.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        checkBoxConfigurePayLater.setText("Pay Later Option");
        checkBoxConfigurePayLater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxConfigurePayLaterActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxConfigurePayLater, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        labelLastServiceDate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelLastServiceDate.setText("Last Service Date: ");
        jPanel1.add(labelLastServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, -1));

        labelServiceDateFormat.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelServiceDateFormat.setText("(dd/mm/yyyy)");
        jPanel1.add(labelServiceDateFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 550, -1, -1));

        buttonSearchDiscountDetails.setText("Search");
        buttonSearchDiscountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchDiscountDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSearchDiscountDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 80, 20));

        buttonEditVehicle1.setText("Edit");
        jPanel1.add(buttonEditVehicle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 100, -1));

        comboBoxDiscountPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxDiscountPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        labelFax1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFax1.setText("Fax:");
        jPanel1.add(labelFax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        buttonSetDiscountPlan1.setText("Set");
        buttonSetDiscountPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetDiscountPlan1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSetDiscountPlan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 70, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSearchDiscountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchDiscountDetailsActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_textFieldSearchDiscountDetailsActionPerformed

    private void textFieldLastServiceDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastServiceDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastServiceDayActionPerformed

    private void textFieldLastServiceMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastServiceMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastServiceMonthActionPerformed

    private void textFieldLastServiceYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastServiceYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastServiceYearActionPerformed

    private void textFieldLastMoTYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastMoTYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastMoTYearActionPerformed

    private void textFieldLastMoTDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastMoTDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastMoTDayActionPerformed

    private void textFieldLastMoTMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastMoTMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastMoTMonthActionPerformed

    private void buttonSearchDiscountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchDiscountDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchDiscountDetailsActionPerformed

    private void buttonSetDiscountPlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetDiscountPlan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSetDiscountPlan1ActionPerformed

    private void checkBoxConfigurePayLaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxConfigurePayLaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxConfigurePayLaterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonConfirmDiscount;
    private javax.swing.JButton buttonDone;
    private javax.swing.JButton buttonEditVehicle1;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonNewVehicle;
    private javax.swing.JButton buttonSaveVehicleChanges;
    private javax.swing.JButton buttonSearchDiscountDetails;
    private javax.swing.JButton buttonSetDiscountPlan1;
    private javax.swing.JCheckBox checkBoxAccountHolder;
    private javax.swing.JCheckBox checkBoxConfigurePayLater;
    private javax.swing.JCheckBox checkBoxDiscountPlan;
    private javax.swing.JComboBox<String> comboBoxDiscountPlan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelChassisNo;
    private javax.swing.JLabel labelColour;
    private javax.swing.JLabel labelCustomerDetails;
    private javax.swing.JLabel labelCustomerInformation;
    private javax.swing.JLabel labelDiscountDetail;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEngineSerialNo;
    private javax.swing.JLabel labelFax1;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelLastMoTDate;
    private javax.swing.JLabel labelLastServiceDate;
    private javax.swing.JLabel labelLoggedIn;
    private javax.swing.JLabel labelMake;
    private javax.swing.JLabel labelMoTDateFormat;
    private javax.swing.JLabel labelModel;
    private javax.swing.JLabel labelPercentage;
    private javax.swing.JLabel labelPostCode;
    private javax.swing.JLabel labelRegistrationNo;
    private javax.swing.JLabel labelServiceDateFormat;
    private javax.swing.JLabel labelTelephone;
    private javax.swing.JLabel labelVariableDiscount;
    private javax.swing.JLabel labelVehicles;
    private javax.swing.JList<String> listBusinessType;
    private javax.swing.JList<String> listVehicles;
    private javax.swing.JTextArea textAreaAddress;
    private javax.swing.JTextField textFieldChassisNo;
    private javax.swing.JTextField textFieldColour;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEnginSerialNo;
    private javax.swing.JTextField textFieldFax;
    private javax.swing.JTextField textFieldFullName;
    private javax.swing.JTextField textFieldLastMoTDay;
    private javax.swing.JTextField textFieldLastMoTMonth;
    private javax.swing.JTextField textFieldLastMoTYear;
    private javax.swing.JTextField textFieldLastServiceDay;
    private javax.swing.JTextField textFieldLastServiceMonth;
    private javax.swing.JTextField textFieldLastServiceYear;
    private javax.swing.JTextField textFieldMake;
    private javax.swing.JTextField textFieldModel;
    private javax.swing.JTextField textFieldPercentage;
    private javax.swing.JTextField textFieldPostCode;
    private javax.swing.JTextField textFieldRegistrationNo;
    private javax.swing.JTextField textFieldSearchDiscountDetails;
    private javax.swing.JTextField textFieldTelephone;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
