/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teamproject;

/**
 *
 * @author ahmetsesli
 */
public class UserAccounts extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public UserAccounts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserAccounts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        buttonDone = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        labelSelectUser = new javax.swing.JLabel();
        buttonNewUser = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        textFieldFirstName = new javax.swing.JTextField();
        buttonEditUser = new javax.swing.JButton();
        labelUserDetail = new javax.swing.JLabel();
        textFieldSearch = new javax.swing.JTextField();
        labelRole = new javax.swing.JLabel();
        textFieldUserID = new javax.swing.JTextField();
        textFieldLastName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        buttonUpdateDetails = new javax.swing.JButton();
        buttonDeleteUser = new javax.swing.JButton();
        comboBoxRole = new javax.swing.JComboBox<>();
        labelUserID = new javax.swing.JLabel();
        textFieldUserDetails = new javax.swing.JTextField();
        labelLoggedIn = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        labelLastName1 = new javax.swing.JLabel();
        textFieldLastName1 = new javax.swing.JTextField();

        setSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUserAccounts.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        labelUserAccounts.setText("User Accounts");
        add(labelUserAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        labelFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labelFirstName.setText("First Name:");
        add(labelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        buttonDone.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonDone.setText("Done");
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });
        add(buttonDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, -1, -1));

        listUsers.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(listUsers);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 1140, 240));

        labelSelectUser.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelSelectUser.setText("Select User:");
        add(labelSelectUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        buttonNewUser.setText("New User");
        buttonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewUserActionPerformed(evt);
            }
        });
        add(buttonNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 130, 30));

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));
        add(textFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 130, -1));

        buttonEditUser.setText("Edit User");
        buttonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditUserActionPerformed(evt);
            }
        });
        add(buttonEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 200, -1));

        labelUserDetail.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelUserDetail.setText("User Details:");
        add(labelUserDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));
        add(textFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, -1));

        labelRole.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labelRole.setText("Role:");
        add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));
        add(textFieldUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 130, -1));
        add(textFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 130, -1));

        labelLastName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labelLastName.setText("Last Name:");
        add(labelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, -1, -1));

        buttonUpdateDetails.setText("Update Details");
        buttonUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateDetailsActionPerformed(evt);
            }
        });
        add(buttonUpdateDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 130, 30));

        buttonDeleteUser.setText("Delete User");
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });
        add(buttonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 130, 30));

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 130, -1));

        labelUserID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labelUserID.setText("Username:");
        add(labelUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        textFieldUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUserDetailsActionPerformed(evt);
            }
        });
        add(textFieldUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 220, 30));

        labelLoggedIn.setText("Logged In as:");
        add(labelLoggedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        buttonExit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, -1, -1));

        buttonBack.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        labelLastName1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labelLastName1.setText("Password:");
        add(labelLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));
        add(textFieldLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDoneActionPerformed

    private void buttonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewUserActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditUserActionPerformed

    private void buttonUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateDetailsActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void textFieldUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUserDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUserDetailsActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.JButton buttonDone;
    private javax.swing.JButton buttonEditUser;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonNewUser;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonUpdateDetails;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelLastName1;
    private javax.swing.JLabel labelLoggedIn;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelSelectUser;
    private javax.swing.JLabel labelUserAccounts;
    private javax.swing.JLabel labelUserDetail;
    private javax.swing.JLabel labelUserID;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldLastName;
    private javax.swing.JTextField textFieldLastName1;
    private javax.swing.JTextField textFieldSearch;
    private javax.swing.JTextField textFieldUserDetails;
    private javax.swing.JTextField textFieldUserID;
    // End of variables declaration//GEN-END:variables
}
